### ISSUE TITLE
Issue with $appsToRemove Logic?

### ISSUE THREAD

**Issue by cclifton7** [PatchMyPCTeam/CustomerTroubleshooting#16]
PowerShell/Cleanup Scripts/2023-11-01/PatchMyPC-IntuneCleanupScript.ps1

I am encountering a within region process in the script PatchMyPC-IntuneCleanupScript.ps1. We only have 1 published app that was affected by the recent bug and the script successfully finds and returns it, but the script ends without a prompt to remove it. I think the issue is with _$appsToRemove.ImmediateBaseObject.Count_ (Line 263) but I'm not certain. I added in a _write-output $appsToRemove.ImmediateBaseObject.Count_ and it returns 0 even though there is 1 app found. I manually added an App ID to the updateIdsToClean array, and the script show 2 apps found then prompts for removal.

My work around was to change line 263 to _If ($appsToRemove) {_ which worked for me but might not be the cleanest solution. Just wondering if anyone else has encountered this?

**Comment by codaamok** [comment]
The script was improved and the function you're referring to was rewritten. Kindly retry the latest copy and let us know if it's still an issue?

**Comment by cclifton7** [comment]
Thanks Adam. Working as designed.
